"""criação da tabela cryptocurrencies

Revision ID: 20e9817d6720
Revises: 8df12390d4f0
Create Date: 2025-07-24 22:16:16.410477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e9817d6720'
down_revision: Union[str, Sequence[str], None] = '8df12390d4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptocurrencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coingecko_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('fully_diluted_valuation', sa.BigInteger(), nullable=True),
    sa.Column('total_volume', sa.BigInteger(), nullable=True),
    sa.Column('high_24h', sa.Float(), nullable=True),
    sa.Column('low_24h', sa.Float(), nullable=True),
    sa.Column('price_change_24h', sa.Float(), nullable=True),
    sa.Column('price_change_percentage_24h', sa.Float(), nullable=True),
    sa.Column('market_cap_change_24h', sa.BigInteger(), nullable=True),
    sa.Column('market_cap_change_percentage_24h', sa.Float(), nullable=True),
    sa.Column('circulating_supply', sa.Float(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('max_supply', sa.Float(), nullable=True),
    sa.Column('ath', sa.Float(), nullable=True),
    sa.Column('ath_change_percentage', sa.Float(), nullable=True),
    sa.Column('ath_date', sa.DateTime(), nullable=True),
    sa.Column('atl', sa.Float(), nullable=True),
    sa.Column('atl_change_percentage', sa.Float(), nullable=True),
    sa.Column('atl_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cryptocurrencies_coingecko_id'), 'cryptocurrencies', ['coingecko_id'], unique=False)
    op.create_index(op.f('ix_cryptocurrencies_id'), 'cryptocurrencies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cryptocurrencies_id'), table_name='cryptocurrencies')
    op.drop_index(op.f('ix_cryptocurrencies_coingecko_id'), table_name='cryptocurrencies')
    op.drop_table('cryptocurrencies')
    # ### end Alembic commands ###
