"""api_key de user obrigatorio

Revision ID: d814f5cca9a6
Revises: 20e9817d6720
Create Date: 2025-07-25 23:43:19.911703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd814f5cca9a6'
down_revision: Union[str, Sequence[str], None] = '20e9817d6720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'api_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'api_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
